### ISSUE TITLE
UX: Add category to list-item in listings

### ISSUE THREAD

**Issue by radermacher** [tpetry/stackbricks-community#11]
At __All databases__ I miss the information about the category for context of an database.
![Screenshot 2022-04-20 11 58 16](https://user-images.githubusercontent.com/1656843/164204014-ba61a47f-df22-43ad-afb2-6c9eb7d42fcb.png)

**Comment by tpetry** [comment]
When a database is organized into folders they are now shown below the database version and port like the dockerhub example. 

Shipped with release `0.7.0`
