### ISSUE TITLE
Create database without password

### ISSUE THREAD

**Issue by marcorieser** [tpetry/stackbricks-community#26]
It would be great to be able to create databases without a password.

**Comment by tpetry** [comment]
I do understand the reasoning, but that's only an option for MySQL/MariaDB and is also very frown upon. Connecting to a database without a password is getting more and more complicated, with many tools removing that feature.

There I won't add this option, just use a very very simple password like `admin`, `test` or whatever you like. In case you forget it, you can also right-click a database and copy the connection string which will include the password.
