### ISSUE TITLE
Error when starting mysql  database

### ISSUE THREAD

**Issue by BrendanBasson4** [tpetry/stackbricks-community#36]
When creating a MySQL database it takes a really long time to start then it errors. I see the container being created but for some reason it disappears. I can start MariaDB just not the latest MySQL.

The error I get is: 
`Could not start container`
`Error connecting to database`

**Comment by BrendanBasson4** [comment]
Closing this as I see it is a duplicate error

**Comment by tpetry** [comment]
Fixed with release `0.9.3`
